## Run the Taskwarrior tests, using stable rust to build TaskChampion.
name: tests

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repos
        run: sudo apt-get update -y

      - name: Install apt packages
        run: sudo apt-get install -y build-essential cmake git uuid-dev faketime locales python3 curl gcovr ninja-build

      - name: Check out this repository
        uses: actions/checkout@v6

      - name: Configure project
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage

      - name: Build project
        run: cmake --build build --target test_runner --target task_executable

      - name: Test project
        run: ctest --test-dir build -j 8 --output-on-failure

      - name: Generate a code coverage report
        uses: threeal/gcovr-action@v1.2.0
        with:
          excludes: |
            build

  cargo-test:
    runs-on: ubuntu-latest
    name: "Cargo Test"

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          # If this version is old enough to cause errors, or older than the
          # TaskChampion MSRV, bump it to the MSRV of the currently-required
          # TaskChampion package; if necessary, bump that version as well.
          toolchain: "1.88.0" # MSRV

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v5
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: test
